mh\BTBundle\Entity\ContentObjectLike:
    type: entity
    table: content_object__like
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        createdDate:
            type: datetime
            nullable: false
            column: created_date
    manyToOne:
        user:
            targetEntity: User
            cascade: [persist]
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
        target:
            targetEntity: ContentObject
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                content_object_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: 
        prePersist: [ prePersist ]
