mh\BTBundle\Entity\PostAttachmentImage:
    type: entity
    table: post_attachment_image
    fields:
        id:
            id: true
            type: integer
            unsigned: true
            nullable: false
            generator:
              strategy: IDENTITY
        filename:
            type: string
            length: 32
            fixed: false
            nullable: false
    manyToOne:
        post:
            targetEntity: Post
            joinColumns:
                post_id:
                    referencedColumnName: id
                    nullable: true
    lifecycleCallbacks: 
        prePersist: [ preUpload ]
        preUpdate: [ preUpload ]
        postPersist: [ upload ]
        postUpdate: [ upload ]
        postRemove: [ removeUpload ]
