mh\BTBundle\Entity\PostImage:
    type: entity
    table: post_image
    fields:
        id:
            id: true
            type: integer
            unsigned: true
            nullable: false
            generator:
              strategy: IDENTITY
        filename:
            type: string
            length: 32
            fixed: false
            nullable: false
    oneToOne:
        post:
            targetEntity: Post
            mappedBy: image
            orphanRemoval: true
    lifecycleCallbacks: 
        prePersist: [ preUpload ]
        preUpdate: [ preUpload ]
        postPersist: [ upload ]
        postUpdate: [ upload ]
        postRemove: [ removeUpload ]
