mh\BTBundle\Entity\Post:
    type: entity
    table: post__post
    repositoryClass: mh\BTBundle\Repository\PostRepository
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        slug:
            type: string
            length: 255
            fixed: false
            nullable: false
            gedmo:
                slug:
                    separator: _
                    style: default
                    fields:
                      - title
        title:
            type: string
            length: 255
            fixed: false
            nullable: false
        subtitle:
            type: string
            length: 255
            fixed: false
            nullable: false
        content:
            type: text
            nullable: false
        createdDate:
            type: datetime
            nullable: false
            column: created_date
        baseRate:
            type: smallint
            nullable: false
            column: base_rate
        moderationStatus:
            type: ModerationStatus
            nullable: false
            column: moderation_status
        isPublished:
            type: boolean
            nullable: false
            column: is_published
        showOnMain:
            type: boolean
            nullable: false
            column: show_on_main
        scores:
            type: smallint
            columnDefinition: SMALLINT NOT NULL DEFAULT '0'
    oneToMany:
        comments:
            targetEntity: PostComment
            cascade: [ remove ]
            mappedBy: post
            orderBy:
                createdDate: DESC
        foreignLinks:
            targetEntity: PostForeignLink
            cascade: [ remove ]
            mappedBy: post
            orderBy:
                createdDate: DESC
    manyToMany:
        tags:
            targetEntity: Tag
            cascade: [ persist ]
            mappedBy: posts
        categories:
            targetEntity: Category
            cascade: [ persist ]
            mappedBy: posts
    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
                    nullable: false
            orphanRemoval: false
        tender:
            targetEntity: Tender
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                tender_id:
                    referencedColumnName: id
            orphanRemoval: false
    oneToOne:
        contentObject:
            cascade: [ persist ]
            targetEntity: ContentObject
            joinColumns:
                content_object_id:
                    referencedColumnName: id
            orphanRemoval: false
        image:
            targetEntity: PostImage
            inversedBy: post
            cascade: [ persist, remove ]
            joinColumns:
                image_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: 
        prePersist: [ prePersist ]
