mh\BTBundle\Entity\PostForeignLink:
    type: entity
    table: post__foreign_link
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        url:
            type: string
            length: 255
            fixed: false
            nullable: false
        createdDate:
            type: datetime
            nullable: false
            column: created_date
        scores:
            type: smallint
            nullable: false
            columnDefinition: SMALLINT NOT NULL DEFAULT '0'
    manyToOne:
        post:
            targetEntity: Post
            joinColumns:
                post_id:
                    referencedColumnName: id
                    nullable: false
            orphanRemoval: false
    lifecycleCallbacks: 
        prePersist: [ prePersist ]
