mh\BTBundle\Entity\UserSession:
    type: entity
    table: user__session
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        ip:
            type: string
            length: 15
            fixed: false
            nullable: true
        userAgent:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: user_agent
        hash:
            type: string
            length: 50
            fixed: false
            nullable: true
        beginDate:
            type: datetime
            nullable: false
            column: begin_date
        endDate:
            type: datetime
            nullable: true
            column: end_date
    manyToOne:
        user:
            targetEntity: User
            cascade: [remove]
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: 
        prePersist: [ prePersist ]
