mh\BTBundle\Entity\UserPasswordReset:
    type: entity
    table: user__password_reset
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
        code:
            type: string
            length: 50
            fixed: false
            nullable: true
    oneToOne:
        user:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: 
        prePersist: [ prePersist ]
