mh\BTBundle\Entity\UserEvent:
    type: entity
    table: user_event
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        targetId:
            type: integer
            unsigned: false
            nullable: false
            column: target_id
        eventType:
            type: string
            length: 32
            fixed: false
            column: event_type
        objectType:
            type: string
            length: 32
            fixed: false
            column: object_type
        createdDate:
            type: datetime
            nullable: false
            column: created_date
    lifecycleCallbacks: 
        prePersist: [ prePersist ]