fast_reg:
    pattern: /fast_req
    defaults: { _controller: BTBundle:Frontend\Ajax:fastReg }

new_comment:
    pattern:  /new_comment
    defaults: { _controller: BTBundle:Frontend\Ajax:newComment }
    
post_search_promt:
    pattern:  /post_search_promt/{tag}
    defaults: { _controller: BTBundle:Frontend\Ajax:postSearchPromt, tag: '' }
    
content_like:
    pattern:  /content_like
    defaults: { _controller: BTBundle:Frontend\Ajax:like }
    
content_complaint:
    pattern:  /content_complaint
    defaults: { _controller: BTBundle:Frontend\Ajax:complaint }
    
best_answer:
    pattern:  /best_answer
    defaults: { _controller: BTBundle:Frontend\Ajax:bestAnswer }
    
more_comments:
    pattern:  /more_comments/{id}
    defaults: { _controller: BTBundle:Frontend\Ajax:moreComments }
    requirements:
        id: "[0-9]+"
        
other_themes_for_post:
    pattern:  /other_themes_for_post/
    defaults: { _controller: BTBundle:Frontend\Ajax:otherThemesForPost }
    
next_events:
    pattern: /next_events/{id}
    defaults: { _controller: BTBundle:Frontend\Ajax:nextEvents, id: '' }
    requirements:
        hash: "[0-9]+"
        
prev_events:
    pattern: /prev_events/{id}
    defaults: { _controller: BTBundle:Frontend\Ajax:prevEvents, id: '' }
    requirements:
        hash: "[0-9]+"
        
user_upload:
    pattern: /upload/{mode}
    defaults: { _controller: BTBundle:Frontend\Ajax:userUpload }
    