list_post:
    pattern:  /posts/
    defaults: { _controller: BTBundle:Frontend\Post:list }

show_post:
    pattern:  /post/{id}/
    defaults: { _controller: BTBundle:Frontend\Post:show }
    requirements:
        id: "[0-9]+"

list_post_by_category:
    pattern:  /category/{slug}/
    defaults: { _controller: BTBundle:Frontend\Post:listByCategory }
    requirements:
        slug: "[0-9a-zA-Z_]+"
        
list_post_by_tag:
    pattern:  /tag/{tag}/
    defaults: { _controller: BTBundle:Frontend\Post:listByTag, tag: '' }

list_post_by_login:
    pattern:  /user/{login}/post/
    defaults: { _controller: BTBundle:Frontend\Post:listByLogin}
    requirements:
        login: "[0-9a-zA-Z_]+"
        
