profile_confirm_email:
    pattern:  /profile/confirm/{code}/
    defaults: { _controller: BTBundle:Frontend\Profile:confirm }
    
profile_login:
    pattern:  /profile/login/
    defaults: { _controller: BTBundle:Frontend\Profile:login }
    
profile_socnet_login:
    pattern:  /profile/login/socnet/{mode}/
    defaults: { _controller: BTBundle:Frontend\Profile:socnetLogin }
    requirements:
        code: "vk|fb|ml|tw|gl"

profile_twitter_oauth:
    pattern:  /profile/login/twitter/oauth/
    defaults: { _controller: BTBundle:Frontend\Profile:twitterOAuth }
    
profile_logout:
    pattern:  /profile/logout/
    defaults: { _controller: BTBundle:Frontend\Profile:logout }
    

 
    