_profile_admin_post:
    resource: "profile_admin_post.yml"
    
_profile_admin_question:
    resource: "profile_admin_question.yml"
    
profile_admin_scores:
    pattern:  /profile/scores/{date}/
    defaults: { _controller: BTBundle:Frontend\ProfileAdmin:scores, date: 'today' }
    requirements:
        date: today|\d\d\d\d-\d\d-\d\d
        
profile_admin_edit:
    pattern:  /profile/edit/
    defaults: { _controller: BTBundle:Frontend\ProfileAdmin:edit }
    
profile_admin_invite_friends:
    pattern:  /profile/invite_friends/
    defaults: { _controller: BTBundle:Frontend\ProfileAdmin:inviteFriends } 