profile_admin_list_question:
    pattern:  /profile/qa/questions/
    defaults: { _controller: BTBundle:Frontend\ProfileAdminQA:list }

profile_admin_new_question:
    pattern:  /qa/new/
    defaults: { _controller: BTBundle:Frontend\ProfileAdminQA:new }

profile_admin_delete_question:
    pattern:  /qa/{id}/delete/
    defaults: { _controller: BTBundle:Frontend\ProfileAdminQA:delete }
    requirements:
        id: "[0-9]+"

profile_admin_new_answer:
    pattern:  /qa/{id}/answer/
    defaults: { _controller: BTBundle:Frontend\ProfileAdminQA:answer }
    requirements:
        id: "[0-9]+"
        

        
