list_question:
    pattern:  /qa/
    defaults: { _controller: BTBundle:Frontend\QA:list }

list_question_by_category:
    pattern:  /category/{slug}/qa/
    defaults: { _controller: BTBundle:Frontend\QA:listByCategory }
    requirements:
        slug: "[0-9a-zA-Z_]+"
        
show_question:
    pattern:  /qa/{id}/
    defaults: { _controller: BTBundle:Frontend\QA:show }
    requirements:
        id: "[0-9]+"

show_answer:
    pattern:  /qa/{qid}/#answer{aid}
    defaults: { _controller: BTBundle:Frontend\QA:show }
    requirements:
        qid: "[0-9]+"
        aid: "[0-9]+"
        
        