_profile_admin:
    resource: "profile_admin.yml"

_profile:
    resource: "profile.yml"
    
_message:
    resource: "message.yml"
    prefix:   /message
    
_ajax:
    resource: "ajax.yml"
    prefix:   /ajax

_question:
    resource: "question.yml"

_post:
    resource: "post.yml"
    
_user:
    resource: "user.yml"

homepage:
    pattern:  /
    defaults: { _controller: BTBundle:Frontend\Default:index }
    
feedback:
    pattern:  /feedback/
    defaults: { _controller: BTBundle:Frontend\Default:feedback }

reg_from_invite:
    pattern:  /from_invite/{code}/
    defaults: { _controller: BTBundle:Frontend\Default:regFromInvite }
    
static_page:
    pattern:  /page/{page}/{subpage}/
    defaults: { _controller: BTBundle:Frontend\Default:staticPage, subpage: '' }