_profile_admin:
    resource: "profile_admin.yml"
    prefix:   /profile/admin

_profile:
    resource: "profile.yml"
    prefix:   /profile
    
_message:
    resource: "message.yml"
    prefix:   /message
    
_ajax:
    resource: "ajax.yml"
    prefix:   /ajax

_question:
    resource: "question.yml"
    prefix:   /question

_post:
    resource: "post.yml"
    prefix:   /posts


homepage:
    pattern:  /
    defaults: { _controller: BTBundle:Frontend\Default:index }
    
users_rating:
    pattern:  /rating
    defaults: { _controller: BTBundle:Frontend\Default:rating }
    
feedback:
    pattern:  /feedback
    defaults: { _controller: BTBundle:Frontend\Default:feedback }

reg_from_invite:
    pattern:  /from_invite/{code}
    defaults: { _controller: BTBundle:Frontend\Default:regFromInvite }
    
static_page:
    pattern:  /page/{page}/{subpage}
    defaults: { _controller: BTBundle:Frontend\Default:staticPage, subpage: '' }

user_upload:
    pattern: /upload/{mode}
    defaults: { _controller: BTBundle:Frontend\Default:userUpload }