users_rating:
    pattern:  /users/rating
    defaults: { _controller: BTBundle:Frontend\User:rating }
    
list_post_by_login:
    pattern:  /user/{login}/posts/
    defaults: { _controller: BTBundle:Frontend\Post:listByLogin}
    requirements:
        login: "[0-9a-zA-Z_]+"
        
user_info:
    pattern:  /user/{login}/
    defaults: { _controller: BTBundle:Frontend\User:info}
    requirements:
        login: "[0-9a-zA-Z_]+"
