imports:
    - { resource: db_parameters.yml }
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: doctrine_extensions.yml }
    
framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    trust_proxy_headers: false # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:  ~
    translator: ~

# Twig Configuration
twig:
    form:
        resources:
            - 'BTBundle:Backend/Form:fields.html.twig'
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        my_temp_dir:            "%kernel.root_dir%/cache"
        vk_app_id:              %vk_app_id%
        fb_app_id:              %fb_app_id%
        ml_app_id:              %ml_app_id%
        tw_app_id:              %tw_app_id%
        gl_app_id:              %gl_app_id%
        od_app_id:              %od_app_id%
        feedback_receivers:     %feedback_receivers%
        count_post_per_page:    %count_post_per_page%
        
# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        #auto_mapping: true
        default_entity_manager: default
        entity_managers:
            default:
                #metadata_cache_driver: apc
                #result_cache_driver: apc
                #query_cache_driver: apc
                connection: default
                mappings:
                   BTBundle: { type: yml, dir: Resources/config/doctrine/ }

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }
                    
genemu_form:
    select2: ~

sonata_admin:
    title:      Сайт.Ру
        
sonata_doctrine_orm_admin:
    templates:
      types:
        list:
          complaints: BTBundle:Backend\Default:list_complaints.html.twig
          html: BTBundle:Backend\Default:list_html.html.twig
          moderation_status: BTBundle:Backend\Default:list_moderation_status.html.twig
        show:
          complaints: BTBundle:Backend\Default:show_complaints.html.twig
          html: BTBundle:Backend\Default:show_html.html.twig
          moderation_status: BTBundle:Backend\Default:show_moderation_status.html.twig

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

        #sonata.admin_doctrine_orm.block.audit:
        #    contexts:   [admin]

        sonata.block.service.text:
        sonata.block.service.rss:

        # Some specific block from the SonataMediaBundle
        #sonata.media.block.media:
        #sonata.media.block.gallery:
        #sonata.media.block.feature_media:

trsteel_ckeditor:
    class: Trsteel\CkeditorBundle\Form\Type\CkeditorType
    transformers: ['strip_js', 'strip_css', 'strip_comments']
    toolbar: ['basicstyles', 'paragraph', 'links', '/', 'insert', 'styles', 'tools']
    toolbar_groups:
        basicstyles: ['Bold','Italic','Underline','Strike','Subscript','Superscript','-','RemoveFormat']
        paragraph: ['NumberedList','BulletedList']
        links: ['Link','Unlink','Anchor']
        insert: ['addFile', 'addImage', 'Table','HorizontalRule']
        styles: ['Styles','Format']
        tools: ['Maximize']
    ui_color: '#E8E8E8'
    startup_outline_blocks: false
    width: 647 #Integer or %
    height: 300 #Integer or %
    language: 'ru-ru'
    filebrowser_upload_url:
        url: relative-url.php?type=file
    external_plugins:
            imagepaste:
                path: bundles/trsteelckeditor/plugins/imagepaste