services:
    form.type.moderation_status:
        class: mh\BTBundle\Form\Backend\ModerationStatusType
        tags:
            - { name: form.type, alias: moderation_status }
    #cache:
    #    class: Doctrine\Common\Cache\ApcCache
    kernel.listener.yourlisener:
        class: mh\BTBundle\BTBundleExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }